### ISSUE TITLE
symbol name / description

### ISSUE THREAD

**Issue by cpfannenmueller** [Circuit2TikZ/CircuiTikZ-Designer#13]
-       Give each symbol a name to use as an ID in tikz
-       Add description text for each symbol

**Comment by JPWiedemann** [comment]
symbol name done in 6693e5f354d37fe423eefe378684c824936e561f for v0.4

**Comment by JPWiedemann** [comment]
done in 43068fc8251f6548e90aa7d8587e57565b2a89af
