### ISSUE TITLE
Make shortcuts work on Mac/unix or add mouse usage again

### ISSUE THREAD

**Issue by cpfannenmueller** [Circuit2TikZ/CircuiTikZ-Designer#17]
Shortcuts do not work on mac / unix as expected currently

**Comment by JPWiedemann** [comment]
@cpfannenmueller please check if f951bc5433c0bac86b419d0f2ad7721f4bd0d13b fixed the problem

**Comment by cpfannenmueller** [comment]
Seems to Work everything. 
Except deleting components. This is currently only on "DEL" what is not avaliable on MacOS keyboards without multiple Keys. Maybe it should be also available by the "Backspace" Key additionally

**Comment by JPWiedemann** [comment]
@cpfannenmueller please check again with 1139795fa799d1d78f2589a956d85dd47348850d and close the issue if it works

**Comment by cpfannenmueller** [comment]
works fine
