### ISSUE TITLE
Selection Box drawn at wrong point

### ISSUE THREAD

**Issue by cpfannenmueller** [Circuit2TikZ/CircuiTikZ-Designer#19]
It seems like the selection box for path components is sometimes drawn at the origin instead of the location where the selected path component itself is located
<img width="608" alt="Bildschirmfoto 2024-08-25 um 13 27 58" src="https://github.com/user-attachments/assets/eb8b901b-b2c8-44f2-9d4c-e8015d39f5d4">

**Comment by JPWiedemann** [comment]
steps to reproduce?

**Comment by cpfannenmueller** [comment]
unclear, currently it comes for all path Compoennts (R,L,...) directly drawn
but it seems that wenn it is drawn from left to right the selection apers at the origin. If it is drawn from right to left the selection box apears at twise the distance to the origin.

![Bildschirmfoto 2024-08-25 um 13 37 44](https://github.com/user-attachments/assets/e75a9774-b5ce-4c56-9a72-c74337450fd8)

**Comment by JPWiedemann** [comment]
cannot reproduce...

**Comment by cpfannenmueller** [comment]
Seen in Safari on MacOS 14.6
