### ISSUE TITLE
Revamp the UI controls to be compatible and intuitive with Windows, Apple and mobile devices

### ISSUE THREAD

**Issue by cpfannenmueller** [Circuit2TikZ/CircuiTikZ-Designer#24]
there seem to be some small issues on mobile devices:

- de-selection of component not possible to change grid size
- drawing wires works not as expected
- old wire ending command is still active here
- add support for very small devices (e.g. phones in portrait mode)
- correct alignment of header on devices with low width
- check for other possible issues on mobile devices (currently only checked on iOS with Firefox)
![image](https://github.com/user-attachments/assets/a9b2bed1-e562-450e-a675-cbb85427d5e5)

**Comment by JPWiedemann** [comment]
I would say that this has a low priority for now. 
Most added features are incompatible with the old touch controls (pre version 0.1) so we have to decide what to do here. Revamping the available tools/ button layout is probably necessary (and adjusting the top banner layout while we are at it).

**Comment by JPWiedemann** [comment]
now mostly working for mobile in 0.5
