### ISSUE TITLE
add missing components

### ISSUE THREAD

**Issue by cpfannenmueller** [Circuit2TikZ/CircuiTikZ-Designer#9]
some components are missing and were not included due to bug in SymbolConvert
They should be also added

**Comment by JPWiedemann** [comment]
Added most missing components which don't require additional logic (or a compete overhaul of the system) due to their variable nature (i.e. ICs, Mux/Demux, ...). Added in d82586566f4b2de0d32ef285e30101ee8469f628 and c64fce6c2fd72466a8f502814ad2b54b037e672a.
